### ISSUE TITLE
Hi! DappRadar problem

### ISSUE THREAD

**Issue by yanrising** [script-money/ens-claim-flashbot-example#1]
Hi! Could you help in a similar situation only with DappRadar Airdrop? Many people have fallen for the tricks of cheaters and lost control over the addresses. Unfortunately, I don't have enough experience to write code based on your code yet.

**Comment by script-money** [comment]
Dappradar requires signature to claim, it's different from ENS or PSP. And the value is too low (about 200u) not worth to save.
