### ISSUE TITLE
Forta.

### ISSUE THREAD

**Issue by DamCzech** [script-money/ens-claim-flashbot-example#11]
Hello King! :)

Please add airdrop Forta Network.

https://airdrop.forta.network/
CLAIM: 0x988a7Bc24A9D0fa49989FB9734bDa30f55760cEb
FORT:  0x41545f8b9472D758bB669ed8EaEEEcD7a9C4Ec29

Is there a general template for building a script?

```
const AIRDROP_ABI = [{
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_amount",
        "type": "uint256"
      },
      {
        "internalType": "bytes32[]",
        "name": "_proof",
        "type": "bytes32[]"
      }
    ],
    "name": "claim",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
}];
```

**Comment by script-money** [comment]
Ok, I will add it

**Comment by script-money** [comment]
https://github.com/script-money/ens-claim-flashbot-example/commit/b30a69926d2605eca945a93fdd5cf6eac4a5565e
