### ISSUE TITLE
This address is not eligible for the FORT token airdrop

### ISSUE THREAD

**Issue by Jephx** [script-money/ens-claim-flashbot-example#12]
i got this message : This address is not eligible for the FORT token airdrop altough my address was eligible
maybe something about airdrop-api because we can't check address anymore, only connect wallet to know that our address is eligible

**Comment by script-money** [comment]
Could you provide your address?

**Comment by Jephx** [comment]
0xB7B739acD0f2417dc397cd34BC5173777BBc6673

thx

**Comment by script-money** [comment]
Forta team has modified the api, we can't get proof and amount directly by request.
I don't have an eligible account so I don't know if a signature is required for getting proof requests.
You can follow the webpage, and use the *develop tools - network - response* to get the index amount and proof.
<img width="1116" alt="Screen Shot 2022-07-11 at 10 56 51" src="https://user-images.githubusercontent.com/74860630/178180458-ab09445b-f9a0-4182-af16-bd6ca829a3d6.png">
Then comment line 54 - 60, fill them to line 61 - 63 and execute.
![Screen Shot 2022-07-11 at 10 54 25](https://user-images.githubusercontent.com/74860630/178180185-cb00ce7f-ee1c-4243-ae40-81ebf2a2a707.png)

**Comment by Jephx** [comment]
hy, now it throw error : overfow ( fault="overfow", operation="Big.Number.from", value=2e+21, code=NUMERIC_FAULT, version=bignumber/5.5.0)
is it signature thing ?

**Comment by script-money** [comment]
the big number should max 1e18 I think.

**Comment by Jephx** [comment]
i change amount to string and work like a charm.

thx very much, you save my live
