### ISSUE TITLE
unclaimed tokens

### ISSUE THREAD

**Issue by luart08** [script-money/ens-claim-flashbot-example#16]
hello sir ! i have unclaimed tokens in project (eth) and staked nfts in same project ! how i can get my nfts and claim tokens then send them to save wallet ! before the hacker notice them ! i can prove to you the wallet ! tnx

**Comment by script-money** [comment]
give me the contract and example transaction

**Comment by luart08** [comment]
this example transaction of claim tokens 0xc21ae9ce247dbca75316af7505f89e4599f078e648ccdf9d571ae451666c36c2

kahiru project

**Comment by script-money** [comment]
check this https://github.com/script-money/ens-claim-flashbot-example/issues/15#issuecomment-1235356736

**Comment by luart08** [comment]
> check this [#15 (comment)](https://github.com/script-money/ens-claim-flashbot-example/issues/15#issuecomment-1235356736)

yes the stones can not be transfer it ! i just need to claim them now cuz they will change the token but every time i need to claim the eth directly gone

**Comment by script-money** [comment]
> > check this [#15 (comment)](https://github.com/script-money/ens-claim-flashbot-example/issues/15#issuecomment-1235356736)
> 
> yes the stones can not be transfer it ! i just need to claim them now cuz they will change the token but every time i need to claim the eth directly gone

The contract claim stones is not verified, it's not possible write code to execute. example:https://etherscan.io/tx/0xf5f4621edda0a2bc61a2d45226a43d377306f22e94012e11f31bd715e6e32ecb

**Comment by luart08** [comment]
> > > check this [#15 (comment)](https://github.com/script-money/ens-claim-flashbot-example/issues/15#issuecomment-1235356736)
> > 
> > 
> > yes the stones can not be transfer it ! i just need to claim them now cuz they will change the token but every time i need to claim the eth directly gone
> 
> The contract claim stones is not verified, it's not possible write code to execute. example:https://etherscan.io/tx/0xf5f4621edda0a2bc61a2d45226a43d377306f22e94012e11f31bd715e6e32ecb

oh! ok thank you anyway

**Comment by script-money** [comment]
> > > > check this [#15 (comment)](https://github.com/script-money/ens-claim-flashbot-example/issues/15#issuecomment-1235356736)
> > > 
> > > 
> > > yes the stones can not be transfer it ! i just need to claim them now cuz they will change the token but every time i need to claim the eth directly gone
> > 
> > 
> > The contract claim stones is not verified, it's not possible write code to execute. example:https://etherscan.io/tx/0xf5f4621edda0a2bc61a2d45226a43d377306f22e94012e11f31bd715e6e32ecb
> 
> oh! ok thank you anyway

the contract owner can claim the token to a new address, you can get help from them.
