### ISSUE TITLE
Transaction Reverted Underflow

### ISSUE THREAD

**Issue by kefan-ManesLAB** [script-money/ens-claim-flashbot-example#17]
Error: TX #1 : execution revertedy SafeMath#sub: UNDERFLOW

Likely to be the issue while estimating gas price

**Comment by kefan-ManesLAB** [comment]
Input mistake on my side while tranferring Opensea Storefront. Sry.

**Comment by myk-coder** [comment]
@kefan-ManesLAB did you get it to work, can you help a brother
