### ISSUE TITLE
Q about mint

### ISSUE THREAD

**Issue by delosv** [script-money/ens-claim-flashbot-example#18]
hello sir ! i really appreciate your work and helping the people ! i was wondering if this code can work with mint cuz i have upcoming good mint but they are connected with my hacked wallet so i can not mint as long as the hackers but burner bot on my wallet.

**Comment by script-money** [comment]
There are no problems, but there are 2 areas that need attention:
1. The mint function may need pass proof or signature, you need to get them from the website.
2. The NFT721 safeTransferFrom needs tokenId but if minting is fast, you can’t predict which tokenId you can get

**Comment by delosv** [comment]
> There are no problems, but there are 2 areas that need attention:
> 
> 1. The mint function may need pass proof or signature, you need to get them from the website.
> 2. The NFT721 safeTransferFrom needs tokenId but if minting is fast, you can’t predict which tokenId you can get

i see thanks ye will take the risk ! is there mint function in this code !

**Comment by script-money** [comment]
> i see thanks ye will take the risk ! is there mint function in this code !

No mining code, You need to implement by yourself
