### ISSUE TITLE
Merge

### ISSUE THREAD

**Issue by 0xWhale** [script-money/ens-claim-flashbot-example#20]

**Comment by script-money** [comment]
> Hi,
> 
> Do you have any idea how the script will work after the changes from PoW to PoS? Are there possibilities?

PoS should work without any change, I will test soon to confirm.

**Comment by 0xWhale** [comment]
> > Hi,
> > Do you have any idea how the script will work after the changes from PoW to PoS? Are there possibilities?
> 
> PoS should work without any change, I will test soon to confirm.

The search for an approver loops. It takes a very long time without success. 
Not included in 1554xxxx....

**Comment by script-money** [comment]
> > > Hi,
> > > Do you have any idea how the script will work after the changes from PoW to PoS? Are there possibilities?
> > 
> > 
> > PoS should work without any change, I will test soon to confirm.
> 
> The search for an approver loops. It takes a very long time without success. Not included in 1554xxxx....
> 
> I feel like it's the RPC's fault https://rpc.flashbots.net

use this https://relay.flashbots.net

**Comment by 0xWhale** [comment]
> > > > Hi,
> > > > Do you have any idea how the script will work after the changes from PoW to PoS? Are there possibilities?
> > > 
> > > 
> > > PoS should work without any change, I will test soon to confirm.
> > 
> > 
> > The search for an approver loops. It takes a very long time without success. Not included in 1554xxxx....
> > I feel like it's the RPC's fault https://rpc.flashbots.net
> 
> use this https://relay.flashbots.net

After the change, an error occurs (ERC20):

Error: network cannot be detected (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.0)
  reason: "Network cannot be detected",
  code: 'NETWORK_ERROR',
  event: 'noNetwork'

**Comment by script-money** [comment]
https://rpc.flashbots.net is work fine now
