### ISSUE TITLE
bad response

### ISSUE THREAD

**Issue by hs7558** [script-money/ens-claim-flashbot-example#24]
![QQ截图20230105170638](https://user-images.githubusercontent.com/35947739/210742491-aec6117e-303d-4f64-9b43-19fab50c6c4b.jpg)
脚哥知道这是什么原因嘛

**Comment by script-money** [comment]
You need to add chainId when build transaction, check [this](https://github.com/script-money/ens-claim-flashbot-example/commit/a192f4b980ae9bf24224de896af03b7f03272c2a)
