### ISSUE TITLE
bro,Can you help write a WTF claim script?

### ISSUE THREAD

**Issue by songbaizhi** [script-money/ens-claim-flashbot-example#3]
The Website: https://fees.wtf/claim

Contract Address: 0xA68Dd8cB83097765263AdAD881Af6eeD479c4a33

Because 0.01ETH needs to be transferred before receiving WTF, I don't know how to script this step, okay.

**Comment by script-money** [comment]
[      { ...await this._WTFClaimContract.populateTransaction.unlock(this._sender, this._referrer), gasLimit: 90000 + Math.floor(0.01 / 200e-9), value: parseUnits('0.01', 'ether') },
](https://github.com/script-money/ens-claim-flashbot-example/blob/3d04a99bec799163688ac8c59b8b9b0a3c818690/src/engine/WTF.ts#L149)
