### ISSUE TITLE
Illuvium

### ISSUE THREAD

**Issue by yanrising** [script-money/ens-claim-flashbot-example#7]
Hi! Need your help or consultation
Site with staking - https://staking.illuvium.io/vesting
Token 0x767FE9EDC9E0dF98E07454847909b5E959D7ca0E - ILV
When you stake ILV tokens to vesting tokens transferred (?) to 0x25121EDDf746c884ddE4619b573A7B10714E2a36 - Illuvium: ILV Core Pool. Vesting staking is time locked. Question - if wallet compromised (autotransfer balance if you try topup) is it possible to transfer the balance to another (uncompromised) wallet? There's no LP tokens for transfer by conventional means. Please give advice if possible. Thank you in advance. If you have any further questions, write me.

**Comment by script-money** [comment]
"it possible to transfer the balance to another (uncompromised) wallet?" Yes, use flashbot
You need bundle two transactions:
1. unlock vesting token or lp from ILV staking contract
2. transfer token or lp to an uncompromised wallet, sushiswap lp token should be transferred
(if lp token can't be transfer, you can also remove lp then transfer ETH and ILV)

**Comment by yanrising** [comment]
Thanks!
